Importing all dependencies

In [ ]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import difflib
from sklearn.metrics.pairwise import cosine_similarity

importing our dataset

In [ ]:
song_data = pd.read_csv('song_data.csv')
print(song_data.head())
song_data.info()


   Index              Song Title  \
0      0               Yeh Dosti   
1      1  Haan Jab Tak Hain Jaan   
2      2             Koi Haseena   
3      3             Holi Ke Din   
4      4       Mehbooba Mehbooba   

                                        Hindi Lyrics  \
0  ['Lyrics', 'Yeh dosti hum nahin todhenge', 'To...   
1  ['Lyrics', 'Ho ... oh oh oh oh oh', 'Haan jab ...   
2  ['Lyrics', 'Koi haseena jab rooth jaati hain t...   
3  ['Lyrics', 'Chalo saheli', 'Chalo saheli', 'Ch...   
4  ['Lyrics', 'Ooh ooh ooh ooh', 'Ooh ooh ooh ooh...   

                                English Translations  
0  ['Translation', 'We will never break our frien...  
1  ['Translation', 'Ho ... oh oh oh oh oh', 'Till...  
2  ['Translation', 'When a beautiful girl throws ...  
3  ['Translation', "Let's go girls", "Let's go gi...  
4  ['Translation', 'Ooh ooh ooh ooh', 'Ooh ooh oo...  
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4230 entries, 0 to 4229
Data columns (total 4 columns):
 #   Colum

Select Main Features

In [ ]:
selected_features = ['Song Title','Hindi Lyrics','English Translations']
print(selected_features)

['Song Title', 'Hindi Lyrics', 'English Translations']


In [ ]:
combined_features = song_data['Song Title'] + ' '+song_data['Hindi Lyrics']+' '+song_data['English Translations']
print(combined_features)

0       Yeh Dosti ['Lyrics', 'Yeh dosti hum nahin todh...
1       Haan Jab Tak Hain Jaan ['Lyrics', 'Ho ... oh o...
2       Koi Haseena ['Lyrics', 'Koi haseena jab rooth ...
3       Holi Ke Din ['Lyrics', 'Chalo saheli', 'Chalo ...
4       Mehbooba Mehbooba ['Lyrics', 'Ooh ooh ooh ooh'...
                              ...                        
4225    Chal Tere Ishq Mein ['Lyrics', 'Joh bhi faisla...
4226    Khairiyat ['Lyrics', 'Aye do jahaan ke malik s...
4227    Dil Jhoom ['Lyrics', 'Yeh shaukiye shararat ye...
4228    Kudmayi ['Lyrics', 'Salma sitaron wali shagna ...
4229    Ve Kamleya ['Lyrics', 'Ve kamleya, ve kamleya'...
Length: 4230, dtype: object


Change Data into numerical features

In [ ]:
vectorizer = TfidfVectorizer()
numerical_feature = vectorizer.fit_transform(combined_features)
print(numerical_feature)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 647496 stored elements and shape (4230, 30595)>
  Coords	Values
  (0, 30372)	0.057261676906194645
  (0, 8568)	0.2105032736786111
  (0, 17075)	0.006876901795450623
  (0, 12273)	0.0891669778578566
  (0, 19339)	0.19602301129453875
  (0, 28303)	0.5197860959349778
  (0, 8783)	0.14853267965460654
  (0, 17304)	0.15330281259256037
  (0, 27822)	0.0905282372255736
  (0, 23892)	0.18850759394171035
  (0, 19141)	0.04747936469893657
  (0, 5764)	0.2069256016280766
  (0, 1474)	0.04196621623858373
  (0, 18235)	0.03885575036526796
  (0, 13496)	0.06611314291798763
  (0, 27827)	0.041347718107489564
  (0, 11363)	0.06053645545810438
  (0, 26895)	0.050000248232935175
  (0, 1742)	0.05657973273697918
  (0, 18231)	0.012754257652674754
  (0, 30293)	0.021494686466276815
  (0, 10484)	0.046900778302661074
  (0, 18224)	0.01397604753522792
  (0, 12948)	0.07067078456637278
  (0, 303)	0.06867940950386124
  :	:
  (4229, 29016)	0.02742369461367758
  (4229, 430

Check the simialrity Scores

In [ ]:
similarity = cosine_similarity(numerical_feature)
print(similarity)


[[1.         0.20067561 0.12618514 ... 0.01904021 0.03807538 0.02643631]
 [0.20067561 1.         0.1871246  ... 0.03741367 0.02227881 0.01637282]
 [0.12618514 0.1871246  1.         ... 0.02175374 0.02154009 0.01636701]
 ...
 [0.01904021 0.03741367 0.02175374 ... 1.         0.03494151 0.03101415]
 [0.03807538 0.02227881 0.02154009 ... 0.03494151 1.         0.04220262]
 [0.02643631 0.01637282 0.01636701 ... 0.03101415 0.04220262 1.        ]]


Main Recommender system

In [ ]:
song_name = input('Enter your favourite song name')
list_of_all_titles = song_data['Song Title'].tolist()
find_close_match = difflib.get_close_matches(song_name,list_of_all_titles)
print(find_close_match)
close_match = find_close_match[0]
print(close_match)
index_of_song = song_data[song_data['Song Title'] == close_match].index[0]
print(index_of_song)
similarity_score = list(enumerate(similarity[index_of_song]))
print(similarity_score)
sorted_similar_score = sorted(similarity_score,key = lambda x:x[1],reverse=True)
print(sorted_similar_score)

print("songs suggested for you are: ")
i = 1

for songs in sorted_similar_score:
  index = songs[0]
  title_of_songs = song_data[song_data.index == index]['Song Title'].values[0]
  if(i<10):
    print(i,title_of_songs)
    i = i+1


Enter your favourite song nameChal Tere Ishq Mein
['Chal Tere Ishq Mein', 'Chal Mere Bhai', 'Chal Mere Bhai']
Chal Tere Ishq Mein
4225
[(0, np.float64(0.04350036903325179)), (1, np.float64(0.05355569427526255)), (2, np.float64(0.02909751266741627)), (3, np.float64(0.18602813962704323)), (4, np.float64(0.02000043255329988)), (5, np.float64(0.07671139871607062)), (6, np.float64(0.16390502889705624)), (7, np.float64(0.09570995451016812)), (8, np.float64(0.16475526608911076)), (9, np.float64(0.03993568032278622)), (10, np.float64(0.04307867324844904)), (11, np.float64(0.10686559952310173)), (12, np.float64(0.05106768625207069)), (13, np.float64(0.11759254837866556)), (14, np.float64(0.02038718315672953)), (15, np.float64(0.00771098566550415)), (16, np.float64(0.033632374842827106)), (17, np.float64(0.15817370186737673)), (18, np.float64(0.06347258048254903)), (19, np.float64(0.1729596120593905)), (20, np.float64(0.13664983172422063)), (21, np.float64(0.09231625477346163)), (22, np.float64(